import React, { useState } from 'react';
import { aiKitchenBatchPlan } from '../services/api/ai';

// v0 scaffold for: No KDS (kitchen-display) integration
// Generated by batch_00 audit. Wire to real API; v0 calls /api/gap-kds-kitchen-display-integration/run.

export default function KdsKitchenDisplayIntegrationPage() {
  const [input, setInput] = useState<string>('');
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const sampleRequests = [
      {
          "label": "Scenario",
          "value": "Run No KDS (kitchen-display) integration for a realistic customer case.\nContext: a team needs a practical recommendation based on incomplete operating data.\nGoal: identify the best action, key risks, missing information, and expected business impact.\nReturn: summary, prioritized action plan, assumptions, and follow-up questions."
      },
      {
          "label": "Data sample",
          "value": "Analyze this No KDS (kitchen-display) integration data sample.\nInput records:\n- Record 1: urgent, customer impact high, owner unassigned\n- Record 2: medium priority, blocked by missing data\n- Record 3: recurring issue, automation opportunity\nReturn structured findings, anomalies, recommendations, and confidence."
      },
      {
          "label": "Executive review",
          "value": "Prepare an executive review for No KDS (kitchen-display) integration.\nAudience: business owner, operations lead, and implementation team.\nInclude impact, risk, estimated effort, decision points, and a concise next-step plan."
      }
  ];

  const applySampleRequest = (value) => {
    setInput(value);
    setError(null);
    setResult(null);
  };
  const [batchResult, setBatchResult] = useState<any>(null);

  async function run() {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const token = (typeof localStorage !== 'undefined') ? localStorage.getItem('token') : null;
      const res = await fetch('/api/gap-kds-kitchen-display-integration/run', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ input }),
      });
      setResult(await res.json());
    } catch (e: any) {
      setError(e?.message || 'Unknown error');
    } finally {
      setLoading(false);
    }
  }

  async function runBatchPlan() {
    setLoading(true);
    setError(null);
    setBatchResult(null);
    try {
      const data = input.trim()
        ? JSON.parse(input)
        : {
          targetWindowMinutes: 12,
          orders: [
            { id: 'A102', dueInMinutes: 5, items: [{ name: 'burger', quantity: 2 }, { name: 'fries', quantity: 1 }] },
            { id: 'A103', dueInMinutes: 11, items: [{ name: 'chicken wrap', quantity: 1 }, { name: 'iced tea', quantity: 2 }] },
          ],
        };
      setBatchResult(await aiKitchenBatchPlan(data));
    } catch (e: any) {
      setError(e?.message || 'Unknown error');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={{ padding: '2rem', maxWidth: '900px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 600 }}>No KDS (kitchen-display) integration</h1>
      <p style={{ color: '#666', marginBottom: '1rem' }}>v0 scaffold.</p>
      <p style={{ color: '#666', marginBottom: '1rem' }}>Paste an order batch JSON payload, or leave blank to run a sample kitchen batch plan.</p>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 10 }}>
          {sampleRequests.map((sample) => (
            <button
              key={sample.label}
              type="button"
              onClick={() => applySampleRequest(sample.value)}
              style={{ padding: '6px 10px', background: '#eef2ff', color: '#1e3a8a', border: '1px solid #c7d2fe', borderRadius: 6, cursor: 'pointer', fontSize: 12, fontWeight: 600 }}
            >
              {sample.label}
            </button>
          ))}
        </div>

      <textarea
        value={input}
        onChange={(e) => setInput(e.target.value)}
        style={{ width: '100%', height: '160px', padding: '12px', border: '1px solid #ddd', borderRadius: '6px', fontFamily: 'monospace' }}
      />
      <div style={{ marginTop: '12px' }}>
        <button onClick={run} disabled={loading} style={{ background: '#0070f3', color: '#fff', padding: '10px 18px', border: 'none', borderRadius: '6px' }}>
          {loading ? 'Running…' : 'Run'}
        </button>
        <button onClick={runBatchPlan} disabled={loading} style={{ background: '#0f766e', color: '#fff', padding: '10px 18px', border: 'none', borderRadius: '6px', marginLeft: 8 }}>
          {loading ? 'Planning…' : 'Kitchen batch plan'}
        </button>
      </div>
      {error && <pre style={{ marginTop: '16px', color: '#c00', background: '#fee', padding: '12px' }}>{error}</pre>}
      {batchResult && <pre style={{ marginTop: '16px', background: '#ecfeff', padding: '12px', overflow: 'auto', maxHeight: '480px' }}>{JSON.stringify(batchResult, null, 2)}</pre>}
      {result && <pre style={{ marginTop: '16px', background: '#f7f7f7', padding: '12px', overflow: 'auto', maxHeight: '480px' }}>{JSON.stringify(result, null, 2)}</pre>}
    </div>
  );
}
