import React, { useState } from 'react';
import { aiKitchenBatchPlan } from '../services/api/ai';

// v0 scaffold for: No KDS (kitchen-display) integration
// Generated by batch_00 audit. Wire to real API; v0 calls /api/gap-kds-kitchen-display-integration/run.

export default function KdsKitchenDisplayIntegrationPage() {
  const [input, setInput] = useState<string>('');
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [batchResult, setBatchResult] = useState<any>(null);

  async function run() {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const token = (typeof localStorage !== 'undefined') ? localStorage.getItem('token') : null;
      const res = await fetch('/api/gap-kds-kitchen-display-integration/run', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ input }),
      });
      setResult(await res.json());
    } catch (e: any) {
      setError(e?.message || 'Unknown error');
    } finally {
      setLoading(false);
    }
  }

  async function runBatchPlan() {
    setLoading(true);
    setError(null);
    setBatchResult(null);
    try {
      const data = input.trim()
        ? JSON.parse(input)
        : {
          targetWindowMinutes: 12,
          orders: [
            { id: 'A102', dueInMinutes: 5, items: [{ name: 'burger', quantity: 2 }, { name: 'fries', quantity: 1 }] },
            { id: 'A103', dueInMinutes: 11, items: [{ name: 'chicken wrap', quantity: 1 }, { name: 'iced tea', quantity: 2 }] },
          ],
        };
      setBatchResult(await aiKitchenBatchPlan(data));
    } catch (e: any) {
      setError(e?.message || 'Unknown error');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={{ padding: '2rem', maxWidth: '900px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 600 }}>No KDS (kitchen-display) integration</h1>
      <p style={{ color: '#666', marginBottom: '1rem' }}>v0 scaffold.</p>
      <p style={{ color: '#666', marginBottom: '1rem' }}>Paste an order batch JSON payload, or leave blank to run a sample kitchen batch plan.</p>
      <textarea
        value={input}
        onChange={(e) => setInput(e.target.value)}
        style={{ width: '100%', height: '160px', padding: '12px', border: '1px solid #ddd', borderRadius: '6px', fontFamily: 'monospace' }}
      />
      <div style={{ marginTop: '12px' }}>
        <button onClick={run} disabled={loading} style={{ background: '#0070f3', color: '#fff', padding: '10px 18px', border: 'none', borderRadius: '6px' }}>
          {loading ? 'Running…' : 'Run'}
        </button>
        <button onClick={runBatchPlan} disabled={loading} style={{ background: '#0f766e', color: '#fff', padding: '10px 18px', border: 'none', borderRadius: '6px', marginLeft: 8 }}>
          {loading ? 'Planning…' : 'Kitchen batch plan'}
        </button>
      </div>
      {error && <pre style={{ marginTop: '16px', color: '#c00', background: '#fee', padding: '12px' }}>{error}</pre>}
      {batchResult && <pre style={{ marginTop: '16px', background: '#ecfeff', padding: '12px', overflow: 'auto', maxHeight: '480px' }}>{JSON.stringify(batchResult, null, 2)}</pre>}
      {result && <pre style={{ marginTop: '16px', background: '#f7f7f7', padding: '12px', overflow: 'auto', maxHeight: '480px' }}>{JSON.stringify(result, null, 2)}</pre>}
    </div>
  );
}
